export enum STATES {
  MENU,
  STORE_NAME,
  PRODUCT_UNIQUE_IDENTIFIER,
  PRODUCT_DESC,
  PRODUCT_PRICE,
  PRODUCT_IMAGE,
  PRODUCT_QUANTITY,
  CHANGE_STORE,
  VIEW_PRODUCTS,
  EDIT_INVENTORY,
  EDIT_INVENTORY_PRODUCT_ID,
  EDIT_INVENTORY_NEW_INVENTORY,
}
export const menuOptions = ["0", "1", "2", "3"];
