"use strict";
exports.__esModule = true;
exports.menuOptions = exports.STATES = void 0;
var STATES;
(function (STATES) {
    STATES[STATES["MENU"] = 0] = "MENU";
    STATES[STATES["STORE_NAME"] = 1] = "STORE_NAME";
    STATES[STATES["PRODUCT_UNIQUE_IDENTIFIER"] = 2] = "PRODUCT_UNIQUE_IDENTIFIER";
    STATES[STATES["PRODUCT_DESC"] = 3] = "PRODUCT_DESC";
    STATES[STATES["PRODUCT_PRICE"] = 4] = "PRODUCT_PRICE";
    STATES[STATES["PRODUCT_IMAGE"] = 5] = "PRODUCT_IMAGE";
    STATES[STATES["PRODUCT_QUANTITY"] = 6] = "PRODUCT_QUANTITY";
    STATES[STATES["CHANGE_STORE"] = 7] = "CHANGE_STORE";
    STATES[STATES["VIEW_PRODUCTS"] = 8] = "VIEW_PRODUCTS";
    STATES[STATES["EDIT_INVENTORY"] = 9] = "EDIT_INVENTORY";
    STATES[STATES["EDIT_INVENTORY_PRODUCT_ID"] = 10] = "EDIT_INVENTORY_PRODUCT_ID";
    STATES[STATES["EDIT_INVENTORY_NEW_INVENTORY"] = 11] = "EDIT_INVENTORY_NEW_INVENTORY";
})(STATES = exports.STATES || (exports.STATES = {}));
exports.menuOptions = ["0", "1", "2", "3"];
